# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	# https://app.vagrantup.com/bento/boxes/ubuntu-20.04
	config.vm.box                   = "bento/ubuntu-20.04"
	A		= true
	config.hostmanager.manage_host 	= true
	config.hostmanager.manage_guest = true
	config.vm.provision :shell, inline: "apt-get install -y auditd audispd-plugins"
	config.vm.provision "docker"
	config.vm.provision :shell, inline: "sysctl -w vm.max_map_count=262144"
	config.vm.provision :shell, inline: "echo -e \"[Service]\nLimitMEMLOCK=infinity\" | SYSTEMD_EDITOR=tee systemctl edit docker.service"
	config.vm.provision :shell, inline: "systemctl daemon-reload"
	config.vm.provision :shell, inline: "systemctl restart docker"

	config.vm.define "node1" do |node1|
		node1.vm.hostname = 'node1'
		node1.vm.network :private_network, ip: "192.168.99.101"
		node1.vm.provider :virtualbox do |v|
			v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
			v.customize ["modifyvm", :id, "--memory", 5000]
			v.customize ["modifyvm", :id, "--name", "node1"]
		end
		node1.vm.provision :shell, inline: "docker swarm join --token SWMTKN-1-48ve5ypcuiq5d2gyazvz5i5y97pk9ngxuoba8rwoqvoqzixzkb-9ir9rb5onrw19x0cqpok4m0ba 192.168.99.1:2377"
	end

    config.vm.define "node2" do |node2|
		node2.vm.hostname = 'node2'
		node2.vm.network :private_network, ip: "192.168.99.102"
		node2.vm.provider :virtualbox do |v|
			v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
			v.customize ["modifyvm", :id, "--memory", 5000]
			v.customize ["modifyvm", :id, "--name", "node2"]
		end
		node2.vm.provision :shell, inline: "docker swarm join --token SWMTKN-1-48ve5ypcuiq5d2gyazvz5i5y97pk9ngxuoba8rwoqvoqzixzkb-9ir9rb5onrw19x0cqpok4m0ba 192.168.99.1:2377"
	end

end
