# https://github.com/elastic/beats/blob/master/filebeat/filebeat.reference.yml

#filebeat.modules:
#  - module: system
#    syslog:
#      enabled: true
#    auth:
#      enabled: true
#  - module: auditd
#    log:
      # - Does not look like Auditd is supported in Alpine linux: https://github.com/linuxkit/linuxkit/issues/52
      # - CentOS does not need us to install the audit system, it ships as standard. If you are using Ubuntu, though,
      # this is probably something you would want to install. (sudo apt-get install -y auditd audispd-plugins)
#      enabled: true


#========================== Filebeat autodiscover ==============================
# See this URL on how to run Apache2 Filebeat module: # https://www.elastic.co/guide/en/beats/filebeat/current/running-on-docker.html
#filebeat.autodiscover:
#  providers:
#    - type: docker
#      # https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover-hints.html
#      # This URL alos contains instructions on multi-line logs
#      hints.enabled: true

#================================ Processors ===================================
processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_locale:
      format: offset
  - add_host_metadata:
      netinfo.enabled: true

#========================== File config input ===============================
#Enable filebeat config reloading
filebeat.config.inputs:
  enabled: true
  path: external/*.yml
  reload.enabled: true
  reload.period: 10s

#========================== File input ===============================
#filebeat.inputs:
#  - type: log
#    paths:
#      - /usr/share/filebeat/external/logs/logstash-tutorial.log
#========================== Logstash output ===============================
output.logstash:
  hosts: ["logstash:5044"]
  username: "elastic"
  password: "1JA2JP8CSzf0eQeJGO4O"

#========================== Elasticsearch output ===============================
#output.elasticsearch:
#  hosts: ["elasticsearch:9200"]
#  username: "elastic"
#  password: "1JA2JP8CSzf0eQeJGO4O"

#============================== Dashboards =====================================
setup.dashboards:
  enabled: true

#============================== Kibana =========================================
setup.kibana:
  host: "http://kibana:5601"
  username: "elastic"
  password: "1JA2JP8CSzf0eQeJGO4O"

#============================== Xpack Monitoring ===============================
xpack.monitoring:
  enabled: true
  elasticsearch:
    hosts: ["elasticsearch:9200"]
    username: "elastic"
    password: "1JA2JP8CSzf0eQeJGO4O"

