version: '3.7'

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "1m"

services:
  # traefik-init adds the command: config to consul, and then quits
  traefik-init:
    <<: *default-opts
    image: traefik:1.7-alpine
    depends_on:
      - consul
    networks:
      - traefik-consul
    command:
      # Use your favourite settings here, but add:
      - storeconfig
      - --api
      #- --api.insecure=true
      # NOTE: you'll want to lower this logLevel for real world stuff
      - --logLevel="DEBUG"
      # NOTE: you'll want to disable this for anything of signifant traffic, or route logs outside stdout
      - --accessLog
      - --docker
      - --docker.endPoint=http://dockersocket:2375
      - --docker.swarmMode
      - --docker.domain=traefik
      - --docker.network=proxy
      - --docker.watch
      - --consul
      - --consul.endpoint=consul:8500
      - --consul.prefix=traefik
      - --defaultentrypoints=http
    deploy:
      restart_policy:
        condition: on-failure

# actual proxy, running on each node, and using direct host ports
  traefik:
    <<: *default-opts
    image: traefik:1.7-alpine
    depends_on:
      - consul
    networks:
      - proxy
      - traefik-consul
      - traefik-docker
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress # traefik dashboard
    command:
      - --consul
      - --consul.endpoint=consul:8500
      - --consul.prefix=traefik
    deploy:
      mode: global
      labels:
        - traefik.port=8080
        - traefik.frontend.rule=Host:traefik.localhost

# stores the proxy config
  consul:
    <<: *default-opts
    image: consul
    command: agent -server -bootstrap-expect=1
    networks:
      - traefik-consul
    volumes:
      - consul:/consul/data
    environment:
      - CONSUL_LOCAL_CONFIG={"server":true}
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_CLIENT_INTERFACE=eth0

# this custom haproxy allows us to move traefik to worker nodes
# while this container listens on managers and only allows
# traefik to connect, read-only, to limited docker api calls
# https://github.com/Tecnativa/docker-socket-proxy
  dockersocket:
    <<: *default-opts
    image: tecnativa/docker-socket-proxy
    networks:
      - traefik-docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # CONTAINERS: 1
      NETWORKS: 1
      SERVICES: 1
      # SWARM: 1
      TASKS: 1
    deploy:
      mode: global

volumes:
  consul:

networks:
  proxy:
    driver: overlay
    name: proxy
  traefik-consul:
    driver: overlay
  traefik-docker:
    driver: overlay
